In [44]:
# 마운트 하기 

In [126]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [127]:
data = pd.read_csv('/content/drive/MyDrive/code/train_AV3.csv')

In [47]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [48]:
import pandas as pd
from io import StringIO

*이탤릭체 텍스트*### Creating data

In [49]:
csv_data = '''
A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
9.0,10.0,11.0,
13.0,14.0,15.0,16.0
'''

In [50]:
df = pd.read_csv(StringIO(csv_data))

In [51]:
df

A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   NaN   8.0
2   9.0  10.0  11.0   NaN
3  13.0  14.0  15.0  16.0

In [52]:
type(df)

pandas.core.frame.DataFrame

In [53]:
'''isnull method returns a dataframe with boolean values 
that indicate whether a cell contians a nemuric value or if data is missing.'''
df.isnull()

A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True
3  False  False  False  False

In [54]:
# The number of missing values per column
df.isnull().sum(axis=0)

A    0
B    0
C    1
D    1
dtype: int64

In [55]:
# The number of missing values per sample
df.isnull().sum(axis=1)

0    0
1    1
2    1
3    0
dtype: int64

### Eliminating samples or features with missing values

In [56]:
# remove missing samples
df.dropna(axis=0)

A     B     C     D
0   1.0   2.0   3.0   4.0
3  13.0  14.0  15.0  16.0

In [57]:
# remove missing columns
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2   9.0  10.0
3  13.0  14.0

In [58]:
# remove rows where all columns are NaN
df.dropna(how='all')

A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   NaN   8.0
2   9.0  10.0  11.0   NaN
3  13.0  14.0  15.0  16.0

In [59]:
# remove rows that have less than 4 real avlues
df.dropna(thresh=4)

A     B     C     D
0   1.0   2.0   3.0   4.0
3  13.0  14.0  15.0  16.0

In [60]:
# only remove rows where NaN appear in specific columns
df.dropna(subset=['C'])

A     B     C     D
0   1.0   2.0   3.0   4.0
2   9.0  10.0  11.0   NaN
3  13.0  14.0  15.0  16.0

### Imputing missing values

In [61]:
#더이상 지원하지 않는 코드 
from sklearn.preprocessing import Imputer
# axis = 0 calculates the column mean
# axis = 1 calculates the row mean
imr = Imputer(missing_values='NaN', strategy='mean', axis=0)

ImportError: ignored

In [62]:
# 아래 코드로 돌려주시면 됩니다. 
from sklearn.impute import SimpleImputer
import numpy as np
imr = SimpleImputer(missing_values = np.nan , strategy = 'mean')

In [63]:
imr = imr.fit(df.values)

In [64]:
imputed_data = imr.transform(df.values)

In [65]:
imputed_data

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  9.66666667,  8.        ],
       [ 9.        , 10.        , 11.        ,  9.33333333],
       [13.        , 14.        , 15.        , 16.        ]])

### Mappling ordinal features

In [66]:
df = pd.DataFrame([
    ['green', 'M', 10.1, 'class1'],
    ['red', 'L', 13.5, 'class2'],
    ['blue', 'XL', 15.3, 'class1']
])

In [67]:
df.columns =['color', 'size', 'price', 'label']

In [68]:
df

color size  price   label
0  green    M   10.1  class1
1    red    L   13.5  class2
2   blue   XL   15.3  class1

In [69]:
size_mapping = {
    'XL': 3,
    'L': 2,
    'M': 1
}

In [70]:
df['size'] = df['size'].map(size_mapping)

In [71]:
df

color  size  price   label
0  green     1   10.1  class1
1    red     2   13.5  class2
2   blue     3   15.3  class1

In [72]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}
inv_size_mapping

{1: 'M', 2: 'L', 3: 'XL'}

In [73]:
df['size'].map(inv_size_mapping)


0     M
1     L
2    XL
Name: size, dtype: object

In [74]:
df

color  size  price   label
0  green     1   10.1  class1
1    red     2   13.5  class2
2   blue     3   15.3  class1

### Encoding class labels

In [75]:

import numpy as np

In [76]:
unique_labels = np.unique(df['label'])
unique_labels

array(['class1', 'class2'], dtype=object)

In [77]:
class_mapping = {label:idx for idx, label in enumerate(unique_labels)}

In [78]:
class_mapping

{'class1': 0, 'class2': 1}

In [79]:
df['label'] = df['label'].map(class_mapping)

In [80]:
df

color  size  price  label
0  green     1   10.1      0
1    red     2   13.5      1
2   blue     3   15.3      0

In [81]:
inv_class_mapping = {v: k for k, v in class_mapping.items()}

In [82]:
df['label'].map(inv_class_mapping)

0    class1
1    class2
2    class1
Name: label, dtype: object

In [83]:
# sklearn LabelEncoder
from sklearn.preprocessing import LabelEncoder

In [84]:
class_le = LabelEncoder()

In [85]:
# fit_transform method is a shortcut for calling fit and transform separately
y = class_le.fit_transform(df['label'].values)

In [86]:
y

array([0, 1, 0])

In [87]:
class_le.inverse_transform(y)

array([0, 1, 0])

### Performing one-hot encoding on nominal features

In [88]:
from sklearn.preprocessing import OneHotEncoder

In [89]:
df

color  size  price  label
0  green     1   10.1      0
1    red     2   13.5      1
2   blue     3   15.3      0

In [90]:
X = df[['color', 'size', 'price']].values

In [91]:
color_le= LabelEncoder()

In [92]:
X[:, 0] = color_le.fit_transform(X[:, 0])

In [93]:
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [94]:
# 기존 코드 오류 발생
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features=[0])
ohe.fit_transform(X).toarray()

TypeError: ignored

In [95]:
# convert sparse matrix representation into a regular(dense) NumPy array
# 위 코드 대신 아래 코드로 돌려주시면 됩니다. 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
#ohe = OneHotEncoder(categories=[0])

ohe = ColumnTransformer([("color", OneHotEncoder(), [0])], remainder = 'passthrough')
ohe.fit_transform(X)

array([[0.0, 1.0, 0.0, 1, 10.1],
       [0.0, 0.0, 1.0, 2, 13.5],
       [1.0, 0.0, 0.0, 3, 15.3]], dtype=object)

In [96]:
# get_dummies method creates dummy features via one-hot encoding, it only converts string columns.
pd.get_dummies(df[['color', 'size', 'price']])

size  price  color_blue  color_green  color_red
0     1   10.1           0            1          0
1     2   13.5           0            0          1
2     3   15.3           1            0          0

In [97]:
# to address multicollinearity, use drop_first
pd.get_dummies(df[['color', 'size', 'price']], drop_first=True)

size  price  color_green  color_red
0     1   10.1            1          0
1     2   13.5            0          1
2     3   15.3            0          0

### Partitioning a dataset into separate training and test sets

In [98]:
df_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data' , header=None)

In [99]:
df_wine

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [100]:
df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols', 'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins', 'Color intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline']

In [101]:
np.unique(df_wine['Class label'])

array([1, 2, 3])

In [102]:
df_wine.head(20)

Class label  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0             1    14.23        1.71  2.43               15.6        127   
1             1    13.20        1.78  2.14               11.2        100   
2             1    13.16        2.36  2.67               18.6        101   
3             1    14.37        1.95  2.50               16.8        113   
4             1    13.24        2.59  2.87               21.0        118   
5             1    14.20        1.76  2.45               15.2        112   
6             1    14.39        1.87  2.45               14.6         96   
7             1    14.06        2.15  2.61               17.6        121   
8             1    14.83        1.64  2.17               14.0         97   
9             1    13.86        1.35  2.27               16.0         98   
10            1    14.10        2.16  2.30               18.0        105   
11            1    14.12        1.48  2.32               16.8         95   
12            1    13.75        1.73  2.41               16.0         89   
13            1    14.75        1.73  2.39               11.4         91   
14            1    14.38        1.87  2.38               12.0        102   
15            1    13.63        1.81  2.70               17.2        112   
16            1    14.30        1.92  2.72               20.0        120   
17            1    13.83        1.57  2.62               20.0        115   
18            1    14.19        1.59  2.48               16.5        108   
19            1    13.64        3.10  2.56               15.2        116   

    Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0            2.80        3.06                  0.28             2.29   
1            2.65        2.76                  0.26             1.28   
2            2.80        3.24                  0.30             2.81   
3            3.85        3.49                  0.24             2.18   
4            2.80        2.69                  0.39             1.82   
5            3.27        3.39                  0.34             1.97   
6            2.50        2.52                  0.30             1.98   
7            2.60        2.51                  0.31             1.25   
8            2.80        2.98                  0.29             1.98   
9            2.98        3.15                  0.22             1.85   
10           2.95        3.32                  0.22             2.38   
11           2.20        2.43                  0.26             1.57   
12           2.60        2.76                  0.29             1.81   
13           3.10        3.69                  0.43             2.81   
14           3.30        3.64                  0.29             2.96   
15           2.85        2.91                  0.30             1.46   
16           2.80        3.14                  0.33             1.97   
17           2.95        3.40                  0.40             1.72   
18           3.30        3.93                  0.32             1.86   
19           2.70        3.03                  0.17             1.66   

    Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0              5.64  1.04                          3.92     1065  
1              4.38  1.05                          3.40     1050  
2              5.68  1.03                          3.17     1185  
3              7.80  0.86                          3.45     1480  
4              4.32  1.04                          2.93      735  
5              6.75  1.05                          2.85     1450  
6              5.25  1.02                          3.58     1290  
7              5.05  1.06                          3.58     1295  
8              5.20  1.08                          2.85     1045  
9              7.22  1.01                          3.55     1045  
10             5.75  1.25                          3.17     1510  
11             5.00  1.17                          2.82     1280  
12             5.60  1.

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
X = df_wine.iloc[:, 1:].values

In [107]:
df_wine.iloc[:, 1:]

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0      14.23        1.71  2.43               15.6        127           2.80   
1      13.20        1.78  2.14               11.2        100           2.65   
2      13.16        2.36  2.67               18.6        101           2.80   
3      14.37        1.95  2.50               16.8        113           3.85   
4      13.24        2.59  2.87               21.0        118           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5         95           1.68   
174    13.40        3.91  2.48               23.0        102           1.80   
175    13.27        4.28  2.26               20.0        120           1.59   
176    13.17        2.59  2.37               20.0        120           1.65   
177    14.13        4.10  2.74               24.5         96           2.05   

     Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280/OD315 of diluted wines  Proline  
0                            3.92     1065  
1                            3.40     1050  
2                            3.17     1185  
3                            3.45     1480  
4                            2.93      735  
..                            ...      ...  
173                          1.74      740  
174                          1.56      750  
175                          1.56      835  
176                          1.62      840  
177                          1.60      560  

[178 rows x 13 columns]

In [105]:
y = df_wine.iloc[:, 0].values

In [108]:
# stratify ensures that both training and test datasets have the same class proportion as the original dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [109]:
X_train.shape

(124, 13)

In [110]:
X_test.shape

(54, 13)

In [111]:
y_train.shape

(124,)

In [112]:
y_test.shape

(54,)

### Bringing features onto the samle scale

In [113]:
ex = np.array([0, 1, 2, 3, 4, 5])

In [114]:
(ex-ex.min())/(ex.max()-ex.min())

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [115]:
(ex-ex.mean())/ex.std()

array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])

In [116]:
from sklearn.preprocessing import MinMaxScaler

In [117]:
data = [[-1, 2], 
        [-0.5, 6], 
        [0, 10], 
        [1, 18]]

In [118]:
mms = MinMaxScaler()

In [119]:
mms.fit_transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [120]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [121]:
stds = StandardScaler()

In [122]:
stds.fit_transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

부터!

### A compelte example

In [123]:
import pandas as pd
import numpy as np

In [124]:

data = pd.read_csv('train_AV3.csv')

FileNotFoundError: ignored

In [128]:
data.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [129]:
data.shape

(614, 13)

### 전처리

In [130]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [131]:
data.Gender.unique()

array(['Male', 'Female', nan], dtype=object)

In [132]:
data.Gender.fillna(data.Gender.mode().values[0],inplace=True)

In [133]:
data['Married'].value_counts()

Yes    398
No     213
Name: Married, dtype: int64

In [134]:
data.Married.unique()

array(['No', 'Yes', nan], dtype=object)

In [135]:
data.Married.mode()

0    Yes
dtype: object

In [136]:
data.Married.fillna(data.Married.mode().values[0],inplace=True)

In [137]:
data.Dependents.unique()

array(['0', '1', '2', '3+', nan], dtype=object)

In [138]:
data['Dependents'].value_counts()

0     345
1     102
2     101
3+     51
Name: Dependents, dtype: int64

In [139]:
data.Dependents.fillna(data.Dependents.mode().values[0], inplace=True)

In [140]:
data['Self_Employed'].value_counts()


No     500
Yes     82
Name: Self_Employed, dtype: int64

In [141]:
 data.Self_Employed.unique()

array(['No', 'Yes', nan], dtype=object)

In [142]:
data.Self_Employed.fillna(data.Self_Employed.mode().values[0],inplace=True)

In [143]:
data['Credit_History'].value_counts()

1.0    475
0.0     89
Name: Credit_History, dtype: int64

In [144]:
data.LoanAmount.unique()

array([ nan, 128.,  66., 120., 141., 267.,  95., 158., 168., 349.,  70.,
       109., 200., 114.,  17., 125., 100.,  76., 133., 115., 104., 315.,
       116., 112., 151., 191., 122., 110.,  35., 201.,  74., 106., 320.,
       144., 184.,  80.,  47.,  75., 134.,  96.,  88.,  44., 286.,  97.,
       135., 180.,  99., 165., 258., 126., 312., 136., 172.,  81., 187.,
       113., 176., 130., 111., 167., 265.,  50., 210., 175., 131., 188.,
        25., 137., 160., 225., 216.,  94., 139., 152., 118., 185., 154.,
        85., 259., 194.,  93., 370., 182., 650., 102., 290.,  84., 242.,
       129.,  30., 244., 600., 255.,  98., 275., 121.,  63., 700.,  87.,
       101., 495.,  67.,  73., 260., 108.,  58.,  48., 164., 170.,  83.,
        90., 166., 124.,  55.,  59., 127., 214., 240.,  72.,  60., 138.,
        42., 280., 140., 155., 123., 279., 192., 304., 330., 150., 207.,
       436.,  78.,  54.,  89., 143., 105., 132., 480.,  56., 159., 300.,
       376., 117.,  71., 490., 173.,  46., 228., 30

In [145]:
data.LoanAmount.fillna(round(data.LoanAmount.mean(),0),inplace=True)

In [146]:
data.Loan_Amount_Term.unique()

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  36.,  84.,  12.])

In [147]:
data.Loan_Amount_Term.fillna(round(data.Loan_Amount_Term.mean(),0), inplace=True)

In [148]:
data.Credit_History.unique()

array([ 1.,  0., nan])

In [149]:
data.Credit_History.fillna(data.Credit_History.mode().values[0], inplace=True)

In [150]:
data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [151]:


data.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [152]:
X,y=data.iloc[:,:-2],data.iloc[:,-1]

In [153]:
X

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0       146.0             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History  
0               1.0  
1               1.0  
2               1.0  
3               1.0  
4               1.0  
..              ...  
609             1.0  
610             1.0  
611             1.0  
612             1.0  
613             0.0  

[614 rows x 11 columns]

In [154]:
y

0      Y
1      N
2      Y
3      Y
4      Y
      ..
609    Y
610    Y
611    Y
612    Y
613    N
Name: Loan_Status, Length: 614, dtype: object

In [ ]:
    # stratify ensures that both training and test datasets have the same class proportion as the original dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [ ]:
#kNN without preprocessing
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
numeric_features = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History']

In [ ]:
knn.fit(X_train[numeric_features], y_train)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test, knn.predict(X_test[numeric_features]))

### Mapping ordinal features

In [ ]:
dependents_mapping = {
    '3+': 4,
    '2': 3,
    '1': 2,
    '0':1

    
}

In [ ]:
data['Dependents'] = data['Dependents'].map(dependents_mapping)

In [ ]:
X_train['Dependents'] = X_train['Dependents'].map(dependents_mapping)

In [ ]:
X_test['Dependents'] = X_test['Dependents'].map(dependents_mapping)

In [ ]:
X_train.head()

### Encoding class labels

In [158]:
from sklearn.preprocessing import LabelEncoder

In [159]:
class_le = LabelEncoder()

In [161]:
X_train.head()

AttributeError: ignored

In [160]:
class_le.fit(X_train['Gender'])

IndexError: ignored

In [156]:
class_le.fit(df)

ValueError: ignored

In [ ]:
y_train = class_le.transform(y_train.values)

In [ ]:
y_test = class_le.transform(y_test.values)

### Performing one-hot encoding on nominal features

In [ ]:
nominal_features = ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area']

In [ ]:
data.head()

In [ ]:
data_dummies = pd.get_dummies(data[nominal_features], drop_first=True)

In [ ]:
data_dummies.head()

In [ ]:
data = pd.concat([data, data_dummies],axis=1)

In [ ]:
data.head()

In [ ]:
data = data.drop(columns=nominal_features)

In [ ]:
data.head()

### Bringing features onto the samle scale

In [ ]:
X = data.drop(columns=['Loan_ID', 'Loan_Status'])
y = data['Loan_Status']


In [ ]:
# stratify ensures that both training and test datasets have the same class proportion as the original dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preproces  sing import StandardScaler

In [ ]:
min_max = MinMaxScaler()

In [ ]:
min_max.fit(X_train)

In [ ]:
train_minmax = min_max.transform(X_train)

In [ ]:
test_minmax = min_max.transform(X_test)

In [ ]:
knn.fit(train_minmax, y_train)

In [ ]:
accuracy_score(y_test, knn.predict(test_minmax))