# Numpy 문제 풀어보기 

1. 균등분포(Uniform distribution)에서 샘플을 추출하고 평균과 분산을 구해보도록 하겠습니다.
    * numpy로 균등분포의 샘플 array를 만들어 주세요. 
    * 샘플 평균과 분산을 구해보자 
    * 평균: 다 더하고 그 길이로 나누기 -> mean
    * 분산: array의 각 값에서 평균을 빼고 값을 제곱한 후, 제곱한 값을 다 더하고 (array의 길이-1) 로 나눠줍니다
    * 7시 20분까지!
    * 샘플의 갯수는 정해져 있지 않아요! 100개 추출해도 됩니다 ㅋㅋㅋ 

In [7]:
import numpy as np 
def get_stat(array):
    # array의 mean과 variance를 리턴해주세요
    avg = array.mean()
    var = array.var(ddof=1)
    return avg, var

def main():
    sample = np.array([1, 2, 3]) # numpy array를 sample에 저장해주세요
    print(get_stat(sample))
    
if __name__=='__main__':
    main()

(0.5012907208252911, 0.08405417736511654)

In [ ]:
sample = np.random.uniform(size=10000)
sample_mean = sample.mean()
sample_var = sample.var(ddof=1)
sample_mean, sample_var

2. 동전을 던져봅시다 - 동전을 던졌을 때 앞면(1)과 뒷면(0)이 나올 확률을 구해보겠습니다. 주어진 숫자 n에 대해서 앞면이 나올 확률, 뒷면이 나올 확률을 구해보세요. 
    * n 이 주어진다 칩시다 
    * 그러면 주어진 n에 대해서 0, 1로 이루어진 numpy array를 만들구요 
    * 0의 확률, 1의 확률을 구해주세요. 
    
**array가 주어졌을 때, 그 array에서 probability 구하는거**

**밑에 get\_prob 함수에서 number가 없을 때** -> array에 어떤 값들이 있던 간에 그 값들 각각에 대해서 probability를 구하는 것

In [21]:
def get_prob(array, number):
    # array를 리스트로 바꿔서 리스트 메소드 중에서 count로 number가 몇개 있는지를 찾아낸 다음에 길이로 나눔
    # prob = list(array).count(number) / len(array)
    # if number == 1:
    # array.sum() / len(array) -> 1이 나올 확률
    
    #prob = 0
    #for cnt in array:
    #    if cnt == number:
    #        prob += 1
    #prob = prob / len(array)
     
    return prob

def main():
    n = 10
    array = np.random.randint(2, size=n)
    prob_head = get_prob(array, 1)
    prob_tail = get_prob(array, 0)
    return prob_head, prob_tail

if __name__ == '__main__':
    res = main()
    print(res)

(0.8, 0.8)


In [22]:
coin_toss = np.random.randint(2, size=10)
number = 0
prob = len(coin_toss[coin_toss == number]) / len(coin_toss)

prob = (coin_toss.sum() / len(coin_toss) if number == 1
        else 1-(coin_toss.sum() / len(coin_toss)))
prob

0.5

3. **min-max scaling vs standardization**
    * numpy array를 생성합니다. shape은 아무거나 상관 없는데, 2d로 설정해주세요. 
        - ex. shape이 2d이면 (3, 5) 처럼 생겼다는 겁니다
        - 컬럼이 5개, row가 3개 
        - 만약에 column_scale = 3이다 -> 그러면 4번째 column이 scaling/standardizing 됩니다 
    * 필요한 함수
        - min-max scaling할 때 -> min, max
        - standardization할 때 -> mean, std
    * 두가지로 진행해봅시다 
        1. column을 정해두고, 그 column에 대해서만 min-max scaling이랑 standardization을 해주세요 
        2. column을 정해두지 않고, column-wise로 min-max scaling이랑 standardization을 해주세요 
    * 무엇이 중요할까요? -> axis

In [24]:
# A: column을 정해두고 그 column에 대해서만 min-max scaling 하기
def min_max_scaling(array, dimension):
    nominator = (array[:, dimension] - array[:, dimension].min())
    denominator = array[:, dimension].max() - array[:, dimension].min()
    array[:, dimension] = nominator / denominator
    return array

def main():
    array = np.random.random(size=(3, 5))
    print(array)
    dimension = 2
    print(min_max_scaling(array, dimension))
    
main()

[[0.58450745 0.31324116 0.17961918 0.08827192 0.40147117]
 [0.49205068 0.65050045 0.69396998 0.27701495 0.89632107]
 [0.67268993 0.02446917 0.47827149 0.05750134 0.82369626]]
[[0.58450745 0.31324116 0.         0.08827192 0.40147117]
 [0.49205068 0.65050045 1.         0.27701495 0.89632107]
 [0.67268993 0.02446917 0.58063935 0.05750134 0.82369626]]


In [27]:
# A: column을 정해두고 그 column에 대해서만 min-max scaling 하기
def min_max_scaling(array):
    return array - array.min(axis=0) / (array.max(axis=0) - array.min(axis=0))

def main():
    array = np.random.random(size=(3, 5))
    print(array)
    dimension = 2
    print(array.min(axis=0))
    #print(min_max_scaling(array, dimension))

main()

[[0.06101302 0.30743894 0.40164684 0.69193446 0.11670178]
 [0.59088847 0.48141797 0.28721936 0.08539095 0.92714071]
 [0.79708177 0.53196246 0.41808793 0.60479704 0.72104427]]
[0.06101302 0.30743894 0.28721936 0.08539095 0.11670178]


9시까지!
4. 계단 오르내리기 
    * 1000번 가위바위보를 했습니다 
    * 이기면 1, 지면 -1 -> 1) 이 어레이를 먼저 만들어 주세요
    * 2) 각 가위바위보를 했을 때의 나의 위치를 구해주시면 됩니다. 
    ```Python
    rps = [-1, 1, 1, -1, 1]
    current_loc = [-1, 0, 1, 0, 1]
    ```
    * 3) 제일 밑으로 내려갔을 때의 위치랑, 제일 위로 올라갔을 때의 위치를 구해주세요. 

In [37]:
rps = np.random.randint(2, size=1000)
rps[rps == 0] = -1
current_loc = rps.cumsum() #cumsum: cumulative sum, 누적합
current_loc.min(), current_loc.max()

(-1, 44)

#### 뭐가 어려울까 -> stackoverflow
1. 코드로 바꾸기가 힘들다 
2. 그냥 어떻게 접근해야 할지도 모르겠다 
3. enumerate 어떻게 쓰는지 모르겠다 
4. 막막하다  
5. def 여러개 들어가면서 엮는거 잘 모르겠다
6. 기초가 튼튼하지 않은 것 같다 
7. 진도가 너무 빨랐다

#### 여러분이 말씀해주신 여러분의 상태
* 파이썬의 문법은 대충 알고 있다 
* 대애충 간단간단하게는 어떻게 해야 할지 알겠다
* 근데 그 간단한 것들이 어우러지면 대략 머리가 하얘진다
* 그리고 그 간단한 것들이 조금만 복잡해져도 눈앞이 흐리다 
* 복잡한거를 봤을 때 설명을 들으면 알겠는데 내가 쓸 자신은 없다

* 뭐부터 해야 할 지 모르겠다 
* 어디에 뭘 써야 되는지도 모르겠다 
* 에러 잡기 힘들다
* 어떻게든 시도는 했는데 안돌아가면 마음이 슬프다 

#### 이런 상태에서 빨리 탈출해보자 
1. print하기 
    * 간단한 것들이 아직 체화가 안되어 있다 -> 그 간단한 것들이 어떻게 결과물이 나오는지 아직 확신이 없다 
2. 문제 풀 때 선행되어야 하는 것 -> 내가 뭘 하겠다 
    * 내가 가지고 있는 것과 최종 목표가 뭔지 내가 명확하게 알고 있다
    * 중간 단계를 설정한다 
3. 머리로만 생각하지 말고 손을 쓴다 
    * 손코딩을 먼저 하고 나서 진짜 코딩을 한다
    * 손코딩을 할 때 각 변수의 값, 타입을 생각해보고 컴퓨터로 실제 돌렸을 때의 결과물을 비교한다