### Evaluation Metrics

In [ ]:
import numpy as np
from sklearn import metrics

In [ ]:
y_pred = [0, 1, 0, 0]

In [ ]:
y_true = [0, 1, 0, 1]

In [ ]:
# TP/TP+FP
metrics.precision_score(y_true, y_pred)

1.0

In [ ]:
# TP/TP+FN
metrics.recall_score(y_true, y_pred)

0.5

In [ ]:
# f1
metrics.f1_score(y_true, y_pred)

0.6666666666666666

In [ ]:
# accuracy
metrics.accuracy_score(y_true, y_pred)

0.75

In [ ]:
# error
1 - metrics.accuracy_score(y_true, y_pred)

0.25

### Cross-Validation

In [ ]:
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import cross_val_score

In [ ]:
iris = datasets.load_iris()

In [ ]:
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [ ]:
clf = svm.SVC(kernel='linear')

In [ ]:
scores = cross_val_score(clf, iris.data, iris.target, scoring='accuracy', cv=5)

In [ ]:
scores

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [ ]:
scores = cross_val_score(clf, iris.data, iris.target, scoring='f1_macro', cv=5)

In [ ]:
scores

array([0.96658312, 1.        , 0.96658312, 0.96658312, 1.        ])

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn import preprocessing

In [ ]:
clf = make_pipeline(preprocessing.StandardScaler(), svm.SVC())
cross_val_score(clf, iris.data, iris.target, cv=5)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [ ]:
#iris.data

In [ ]:
from sklearn.model_selection import cross_val_predict
clf = svm.SVC(kernel='linear')
y_pred = cross_val_predict(clf, iris.data, iris.target, cv=5)

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# Cross-Validation iterator (K-Fold)
from sklearn.model_selection import KFold
X = ["a", "b", "c", "d"]
kf = KFold(n_splits=2)
for train, test in kf.split(X):
    print('{} {}'.format(train, test))

[2 3] [0 1]
[0 1] [2 3]


In [ ]:
# Cross-Validation iterator (Repeated K-Fold)
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
random_state = 1
rkf = RepeatedKFold(n_splits=2, n_repeats=3, random_state=random_state)
for train, test in rkf.split(X):
    print('{} {}'.format(train, test))

[0 1] [2 3]
[2 3] [0 1]
[1 3] [0 2]
[0 2] [1 3]
[0 1] [2 3]
[2 3] [0 1]


In [ ]:
# Cross-Validation iterator (Leave-One-Out)
from sklearn.model_selection import LeaveOneOut
X = [1, 2, 3, 4]
loo = LeaveOneOut()
for train, test in loo.split(X):
    print('{} {}'.format(train, test))

[1 2 3] [0]
[0 2 3] [1]
[0 1 3] [2]
[0 1 2] [3]


In [ ]:
# Cross-Validation iterator (Leave-P-Out)
from sklearn.model_selection import LeavePOut
X = np.ones(5)
lpo = LeavePOut(p=2)
for train, test in lpo.split(X):
    print('{} {}'.format(train, test))

[2 3 4] [0 1]
[1 3 4] [0 2]
[1 2 4] [0 3]
[1 2 3] [0 4]
[0 3 4] [1 2]
[0 2 4] [1 3]
[0 2 3] [1 4]
[0 1 4] [2 3]
[0 1 3] [2 4]
[0 1 2] [3 4]
