In [ ]:
import pandas as pd
from io import StringIO

### Creating data

In [ ]:
csv_data = '''
A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
9.0,10.0,11.0,
13.0,14.0,15.0,16.0
'''

In [ ]:
df = pd.read_csv(StringIO(csv_data))

In [ ]:
df

A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   NaN   8.0
2   9.0  10.0  11.0   NaN
3  13.0  14.0  15.0  16.0

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
'''isnull method returns a dataframe with boolean values 
that indicate whether a cell contians a nemuric value or if data is missing.'''
df.isnull()

A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True
3  False  False  False  False

In [ ]:
# The number of missing values per column
df.isnull().sum(axis=0)

A    0
B    0
C    1
D    1
dtype: int64

In [ ]:
# The number of missing values per sample
df.isnull().sum(axis=1)

0    0
1    1
2    1
3    0
dtype: int64

### Eliminating samples or features with missing values

In [ ]:
# remove missing samples
df.dropna(axis=0)

A     B     C     D
0   1.0   2.0   3.0   4.0
3  13.0  14.0  15.0  16.0

In [ ]:
# remove missing columns
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2   9.0  10.0
3  13.0  14.0

In [ ]:
# remove rows where all columns are NaN
df.dropna(how='all')

A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   NaN   8.0
2   9.0  10.0  11.0   NaN
3  13.0  14.0  15.0  16.0

In [ ]:
# remove rows that have less than 4 real avlues
df.dropna(thresh=4)

A     B     C     D
0   1.0   2.0   3.0   4.0
3  13.0  14.0  15.0  16.0

In [ ]:
# only remove rows where NaN appear in specific columns
df.dropna(subset=['C'])

A     B     C     D
0   1.0   2.0   3.0   4.0
2   9.0  10.0  11.0   NaN
3  13.0  14.0  15.0  16.0

### Imputing missing values

In [ ]:
#더이상 지원하지 않는 코드 
from sklearn.preprocessing import Imputer
# axis = 0 calculates the column mean
# axis = 1 calculates the row mean
imr = Imputer(missing_values='NaN', strategy='mean', axis=0)

ImportError: ignored

In [ ]:
# 아래 코드로 돌려주시면 됩니다. 
from sklearn.impute import SimpleImputer
import numpy as np
imr = SimpleImputer(missing_values = np.nan , strategy = 'mean')

In [ ]:
imr = imr.fit(df.values)

In [ ]:
imputed_data = imr.transform(df.values)

In [ ]:
imputed_data

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  9.66666667,  8.        ],
       [ 9.        , 10.        , 11.        ,  9.33333333],
       [13.        , 14.        , 15.        , 16.        ]])

### Mappling ordinal features

In [ ]:
df = pd.DataFrame([
    ['green', 'M', 10.1, 'class1'],
    ['red', 'L', 13.5, 'class2'],
    ['blue', 'XL', 15.3, 'class1']
])

In [ ]:
df.columns =['color', 'size', 'price', 'label']

In [ ]:
df

color size  price   label
0  green    M   10.1  class1
1    red    L   13.5  class2
2   blue   XL   15.3  class1

In [ ]:
size_mapping = {
    'XL': 3,
    'L': 2,
    'M': 1
}

In [ ]:
df['size'] = df['size'].map(size_mapping)

In [ ]:
df

color  size  price   label
0  green     1   10.1  class1
1    red     2   13.5  class2
2   blue     3   15.3  class1

In [ ]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}
inv_size_mapping

{1: 'M', 2: 'L', 3: 'XL'}

In [ ]:
df['size'].map(inv_size_mapping)


0     M
1     L
2    XL
Name: size, dtype: object

In [ ]:
df

color  size  price   label
0  green     1   10.1  class1
1    red     2   13.5  class2
2   blue     3   15.3  class1

### Encoding class labels

In [ ]:
import numpy as np

In [ ]:
unique_labels = np.unique(df['label'])
unique_labels

array([0, 1])

In [ ]:
class_mapping = {label:idx for idx, label in enumerate(unique_labels)}

In [ ]:
class_mapping

{'class1': 0, 'class2': 1}

In [ ]:
df['label'] = df['label'].map(class_mapping)

In [ ]:
df

color  size  price  label
0  green     1   10.1      0
1    red     2   13.5      1
2   blue     3   15.3      0

In [ ]:
inv_class_mapping = {v: k for k, v in class_mapping.items()}

In [ ]:
df['label'].map(inv_class_mapping)

0    class1
1    class2
2    class1
Name: label, dtype: object

In [ ]:
# sklearn LabelEncoder
from sklearn.preprocessing import LabelEncoder

In [ ]:
class_le = LabelEncoder()

In [ ]:
# fit_transform method is a shortcut for calling fit and transform separately
y = class_le.fit_transform(df['label'].values)

In [ ]:
y

array([0, 1, 0])

In [ ]:
class_le.inverse_transform(y)

array([0, 1, 0])

### Performing one-hot encoding on nominal features

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df

color  size  price  label
0  green     1   10.1      0
1    red     2   13.5      1
2   blue     3   15.3      0

In [ ]:
X = df[['color', 'size', 'price']].values

In [ ]:
color_le= LabelEncoder()

In [ ]:
X[:, 0] = color_le.fit_transform(X[:, 0])

In [ ]:
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [ ]:
# 기존 코드 오류 발생
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features=[0])
ohe.fit_transform(X).toarray()

In [ ]:
# convert sparse matrix representation into a regular(dense) NumPy array
# 위 코드 대신 아래 코드로 돌려주시면 됩니다. 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
#ohe = OneHotEncoder(categories=[0])

ohe = ColumnTransformer([("color", OneHotEncoder(), [0])], remainder = 'passthrough')
ohe.fit_transform(X)

<178x138 sparse matrix of type '<class 'numpy.float64'>'
	with 2314 stored elements in Compressed Sparse Row format>

In [ ]:
# get_dummies method creates dummy features via one-hot encoding, it only converts string columns.
pd.get_dummies(df[['color', 'size', 'price']])

size  price  color_blue  color_green  color_red
0     1   10.1           0            1          0
1     2   13.5           0            0          1
2     3   15.3           1            0          0

In [ ]:
# to address multicollinearity, use drop_first
pd.get_dummies(df[['color', 'size', 'price']], drop_first=True)

size  price  color_green  color_red
0     1   10.1            1          0
1     2   13.5            0          1
2     3   15.3            0          0

### Partitioning a dataset into separate training and test sets

In [ ]:
df_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data' , header=None)

In [ ]:
df_wine

0      1     2     3     4    5   ...    8     9      10    11    12    13
0     1  14.23  1.71  2.43  15.6  127  ...  0.28  2.29   5.64  1.04  3.92  1065
1     1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28   4.38  1.05  3.40  1050
2     1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81   5.68  1.03  3.17  1185
3     1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18   7.80  0.86  3.45  1480
4     1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82   4.32  1.04  2.93   735
..   ..    ...   ...   ...   ...  ...  ...   ...   ...    ...   ...   ...   ...
173   3  13.71  5.65  2.45  20.5   95  ...  0.52  1.06   7.70  0.64  1.74   740
174   3  13.40  3.91  2.48  23.0  102  ...  0.43  1.41   7.30  0.70  1.56   750
175   3  13.27  4.28  2.26  20.0  120  ...  0.43  1.35  10.20  0.59  1.56   835
176   3  13.17  2.59  2.37  20.0  120  ...  0.53  1.46   9.30  0.60  1.62   840
177   3  14.13  4.10  2.74  24.5   96  ...  0.56  1.35   9.20  0.61  1.60   560

[178 rows x 14 columns]

In [ ]:
df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols', 'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins', 'Color intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline']

In [ ]:
np.unique(df_wine['Class label'])

array([1, 2, 3])

In [ ]:
df_wine.head(20)

Class label  Alcohol  ...  OD280/OD315 of diluted wines  Proline
0             1    14.23  ...                          3.92     1065
1             1    13.20  ...                          3.40     1050
2             1    13.16  ...                          3.17     1185
3             1    14.37  ...                          3.45     1480
4             1    13.24  ...                          2.93      735
5             1    14.20  ...                          2.85     1450
6             1    14.39  ...                          3.58     1290
7             1    14.06  ...                          3.58     1295
8             1    14.83  ...                          2.85     1045
9             1    13.86  ...                          3.55     1045
10            1    14.10  ...                          3.17     1510
11            1    14.12  ...                          2.82     1280
12            1    13.75  ...                          2.90     1320
13            1    14.75  ...                          2.73     1150
14            1    14.38  ...                          3.00     1547
15            1    13.63  ...                          2.88     1310
16            1    14.30  ...                          2.65     1280
17            1    13.83  ...                          2.57     1130
18            1    14.19  ...                          2.82     1680
19            1    13.64  ...                          3.36      845

[20 rows x 14 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df_wine.iloc[:, 1:].values

In [ ]:
y = df_wine.iloc[:, 0].values

In [ ]:
# stratify ensures that both training and test datasets have the same class proportion as the original dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [ ]:
X_train.shape

(124, 13)

In [ ]:
X_test.shape

(54, 13)

In [ ]:
y_train.shape

(124,)

In [ ]:
y_test.shape

(54,)

### Bringing features onto the samle scale

In [ ]:
ex = np.array([0, 1, 2, 3, 4, 5])

In [ ]:
(ex-ex.min())/(ex.max()-ex.min())

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
(ex-ex.mean())/ex.std()

array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
data = [[-1, 2], 
        [-0.5, 6], 
        [0, 10], 
        [1, 18]]

In [ ]:
mms = MinMaxScaler()

In [ ]:
mms.fit_transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [ ]:
stds = StandardScaler()

In [ ]:
stds.fit_transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

부터!

### A complete example

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('train_AV3.csv')

FileNotFoundError: ignored

In [ ]:
data.head()

In [ ]:
data.shape

### 전처리

In [ ]:
data.isnull().sum()

In [ ]:
data.Gender.unique()

In [ ]:
data.Gender.fillna(data.Gender.mode().values[0],inplace=True)

In [ ]:
data['Married'].value_counts()

In [ ]:
data.Married.unique()

In [ ]:
data.Married.mode()

In [ ]:
data.Married.fillna(data.Married.mode().values[0],inplace=True)

In [ ]:
data.Dependents.unique()

In [ ]:
data['Dependents'].value_counts()

In [ ]:
data.Dependents.fillna(data.Dependents.mode().values[0], inplace=True)

In [ ]:
data['Self_Employed'].value_counts()


In [ ]:
data.Self_Employed.unique()

In [ ]:
data.Self_Employed.fillna(data.Self_Employed.mode().values[0],inplace=True)

In [ ]:
data['Credit_History'].value_counts()

In [ ]:
data.LoanAmount.unique()

In [ ]:
data.LoanAmount.fillna(round(data.LoanAmount.mean(),0),inplace=True)

In [ ]:
data.Loan_Amount_Term.unique()

In [ ]:
data.Loan_Amount_Term.fillna(round(data.Loan_Amount_Term.mean(),0), inplace=True)

In [ ]:
data.Credit_History.unique()

In [ ]:
data.Credit_History.fillna(data.Credit_History.mode().values[0], inplace=True)

In [ ]:
data.isnull().sum()

In [ ]:
data.dtypes

In [ ]:
X,y=data.iloc[:,:-2],data.iloc[:,-1]

In [ ]:
X

In [ ]:
y

In [ ]:
# stratify ensures that both training and test datasets have the same class proportion as the original dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [ ]:
#kNN without preprocessing
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
numeric_features = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History']

In [ ]:
knn.fit(X_train[numeric_features], y_train)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test, knn.predict(X_test[numeric_features]))

### Mapping ordinal features

In [ ]:
dependents_mapping = {
    '3+': 4,
    '2': 3,
    '1': 2,
    '0':1
}

In [ ]:
data['Dependents'] = data['Dependents'].map(dependents_mapping)

In [ ]:
X_train['Dependents'] = X_train['Dependents'].map(dependents_mapping)

In [ ]:
X_test['Dependents'] = X_test['Dependents'].map(dependents_mapping)

In [ ]:
X_train.head()

### Encoding class labels

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
class_le = LabelEncoder()

In [ ]:
class_le.fit(y_train.values)

In [ ]:
y_train = class_le.transform(y_train.values)

In [ ]:
y_test = class_le.transform(y_test.values)

### Performing one-hot encoding on nominal features

In [ ]:
nominal_features = ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area']

In [ ]:
data.head()

In [ ]:
data_dummies = pd.get_dummies(data[nominal_features], drop_first=True)

In [ ]:
data_dummies.head()

In [ ]:
data = pd.concat([data, data_dummies],axis=1)

In [ ]:
data.head()

In [ ]:
data = data.drop(columns=nominal_features)

In [ ]:
data.head()

### Bringing features onto the samle scale

In [ ]:
X = data.drop(columns=['Loan_ID', 'Loan_Status'])
y = data['Loan_Status']


In [ ]:
# stratify ensures that both training and test datasets have the same class proportion as the original dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [ ]:
min_max = MinMaxScaler()

In [ ]:
min_max.fit(X_train)

In [ ]:
train_minmax = min_max.transform(X_train)

In [ ]:
test_minmax = min_max.transform(X_test)

In [ ]:
knn.fit(train_minmax, y_train)

In [ ]:
accuracy_score(y_test, knn.predict(test_minmax))