In [2]:
import numpy as np 

In [3]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [5]:
np.random.randn()

-0.6257758441341539

In [6]:
np.random.randn(10)

array([-0.79597086,  2.05362395,  2.27095784, -0.60093115, -1.29793454,
       -0.39660142,  1.76636265,  0.19895792,  0.06294195, -0.76077055])

In [7]:
np.random.randn(2, 5)

array([[ 0.92580506, -2.73036118, -0.19573803,  0.82953504, -1.01057472],
       [-1.15240169,  1.61168044,  1.34113499, -1.59672788, -0.81345183]])

In [9]:
np.random.randn(2, 2, 3)

array([[[-1.08198255e+00,  3.45661833e-01,  4.21941022e-01],
        [-1.84612546e-03,  1.80907447e+00,  1.48641492e+00]],

       [[ 1.12854539e+00, -1.56070752e+00, -4.47295207e-01],
        [ 2.15506207e+00,  4.28849032e-01,  3.08185478e-01]]])

In [10]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [11]:
np.random.randint(10)

4

In [12]:
np.random.randint(1, 11)

3

In [14]:
a = np.random.randint(1, 11, size=(2,3))

In [15]:
a

array([[ 8,  8, 10],
       [10,  7,  5]])

In [17]:
list(a)

[array([ 8,  8, 10]), array([10,  7,  5])]

In [18]:
a[0]

array([ 8,  8, 10])

In [19]:
type(a[0])

numpy.ndarray

In [24]:
# 벡터던 행렬이던 텐서던 임의의 numpy ndarray가 주어졌을 때 중복값을 없애보자
# 중복값이 몇개가 있는지 알아야 할 것 같다 
# 저의 방법: 딕셔너리 하나 만들자 
# 딕셔너리의 키: random number, 값: 리스트, 위치(리스트)
# 일단은 행렬이 들어왔다고 생각해보자

random_numbers = {}
for row_idx, a_row in enumerate(a):
    for elem_idx, a_elem in enumerate(a_row):
        if a_elem in random_numbers: 
            random_numbers[a_elem].append([row_idx, elem_idx]) 
        else:  
            random_numbers[a_elem] = [[row_idx, elem_idx]]
            
# 대충 이렇게 하면 될 것 같은데...?
for key, val in random_numbers.items():
    if len(val) != 1:
        temp = np.random.randint(1, 11)
        while (temp in random_numbers.keys()):
            temp = np.random.randint(1, 11)
            
        change = val.pop(0)
        a[change[0], change[1]] = temp

{8: [[0, 0], [0, 1]], 10: [[0, 2], [1, 0]], 7: [[1, 1]], 5: [[1, 2]]}

PEP 
* 파이썬 사용자 끼리 파이썬을 어떻게 쓰면 좋겠다 하는 제안
* 강제성은 없으나 많은 사람들이 그렇게 쓰고, 이미 익숙해져 있어서 협업할 때 **가독성**을 위해 지켜주는 것이 좋다 
* 파이썬 들여쓰기는 스페이스 4개가 국룰
* py파일이던 아니면 노트북 파일이던 string의 경우에, 한번 작은 따옴표 썼으면 작은 따옴표로 통일하는게 국룰

In [53]:
# docstring: ''' 혹은 """
python_string = "1"

def life(emotion):
    '''
    This function illustrates life and your emotion
    :param emotion: string
    '''
    # comment
    return 'Life is '+emotion

In [54]:
help(life)

Help on function life in module __main__:

life(emotion)
    This function illustrates life and your emotion
    :param emotion: string



In [44]:
c

array([[ 6,  4,  3,  7,  6],
       [ 8,  3,  6, 10,  7],
       [ 5,  2, 10,  6,  9]])

In [46]:
c[0, 0] = 11
c

array([[11,  4,  3,  7,  6],
       [ 8,  3,  6, 10,  7],
       [ 5,  2, 10,  6,  9]])

In [47]:
c[:, 1]

array([4, 3, 2])

In [48]:
# broadcasting
c[:, 1] = 1
c

array([[11,  1,  3,  7,  6],
       [ 8,  1,  6, 10,  7],
       [ 5,  1, 10,  6,  9]])

In [49]:
c[:, 1] = [1, 2, 3]
c

array([[11,  1,  3,  7,  6],
       [ 8,  2,  6, 10,  7],
       [ 5,  3, 10,  6,  9]])

In [50]:
# 아예 숫자만 주던가 아니면 차원을 맞춰서 값을 바꿔치기해야 함
c[:, 1] = [1, 2]
c

ValueError: cannot copy sequence with size 2 to array axis with dimension 3

## Numpy array indexing & slicing

* indexing 혹은 slicing으로 원소를 추출할 수 있다 
* indexing 혹은 slicing으로 원소를 바꿀 수 있다

In [27]:
b = [1, 2, 3]
b[-1]

3

In [28]:
a

array([[ 8,  8, 10],
       [10,  7,  5]])

In [29]:
a[0]

array([ 8,  8, 10])

In [30]:
a[1]

array([10,  7,  5])

In [31]:
a[-1]

array([10,  7,  5])

In [32]:
a[0][0]

8

In [34]:
a[1, 1]

7

In [37]:
# a의 모든 row, 1번 column
a[:, 1]

array([8, 7])

In [38]:
c = np.random.randint(1, 11, size=(3, 5))
c

array([[ 6,  4,  3,  7,  6],
       [ 8,  3,  6, 10,  7],
       [ 5,  2, 10,  6,  9]])

In [41]:
c[:2, 1:4]

array([[ 4,  3,  7],
       [ 3,  6, 10]])

In [55]:
c

array([[11,  1,  3,  7,  6],
       [ 8,  2,  6, 10,  7],
       [ 5,  3, 10,  6,  9]])

In [57]:
# transpose라는 method를 사용한다
c.transpose()

array([[11,  8,  5],
       [ 1,  2,  3],
       [ 3,  6, 10],
       [ 7, 10,  6],
       [ 6,  7,  9]])

In [58]:
# attribute에 저장된 것을 불러온다
c.T

array([[11,  8,  5],
       [ 1,  2,  3],
       [ 3,  6, 10],
       [ 7, 10,  6],
       [ 6,  7,  9]])

In [63]:
c.shape

(3, 5)

In [66]:
c_flat = c.flatten()
c_flat.shape

(15,)

In [68]:
c_flat

array([11,  1,  3,  7,  6,  8,  2,  6, 10,  7,  5,  3, 10,  6,  9])

In [69]:
c_flat[3] = 111 
c_flat

array([ 11,   1,   3, 111,   6,   8,   2,   6,  10,   7,   5,   3,  10,
         6,   9])

In [70]:
c

array([[11,  1,  3,  7,  6],
       [ 8,  2,  6, 10,  7],
       [ 5,  3, 10,  6,  9]])

In [65]:
c

array([[11,  1,  3,  7,  6],
       [ 8,  2,  6, 10,  7],
       [ 5,  3, 10,  6,  9]])

In [71]:
c_ravel = c.ravel()
c_ravel

array([11,  1,  3,  7,  6,  8,  2,  6, 10,  7,  5,  3, 10,  6,  9])

In [72]:
c_ravel[3] = 111
c_ravel

array([ 11,   1,   3, 111,   6,   8,   2,   6,  10,   7,   5,   3,  10,
         6,   9])

In [73]:
c

array([[ 11,   1,   3, 111,   6],
       [  8,   2,   6,  10,   7],
       [  5,   3,  10,   6,   9]])

In [75]:
c.shape

(3, 5)

In [88]:
c.reshape((5, 3))

array([[ 11,   1,   3],
       [111,   6,   8],
       [  2,   6,  10],
       [  7,   0,   0],
       [  0,   0,   0]])

### Reshape vs Resize
1. Reshape: 수정 전 후의 어레이 item 갯수가 일치해야 모양을 바꿈, return 바뀐 어레이
2. Resize: 수정 전 후의 어레이 item 갯수가 일치하지 않아도 모양을 바꿈, return None

In [90]:
help(c.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function
    
    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.



In [89]:
help(c.resize)

Help on built-in function resize:

resize(...) method of numpy.ndarray instance
    a.resize(new_shape, refcheck=True)
    
    Change shape and size of array in-place.
    
    Parameters
    ----------
    new_shape : tuple of ints, or `n` ints
        Shape of resized array.
    refcheck : bool, optional
        If False, reference count will not be checked. Default is True.
    
    Returns
    -------
    None
    
    Raises
    ------
    ValueError
        If `a` does not own its own data or references or views to it exist,
        and the data memory must be changed.
        PyPy only: will always raise if the data memory must be changed, since
        there is no reliable way to determine if references or views to it
        exist.
    
    SystemError
        If the `order` keyword argument is specified. This behaviour is a
        bug in NumPy.
    
    See Also
    --------
    resize : Return a new array with the specified shape.
    
    Notes
    -----
    This realloca

In [83]:
c.resize((5, 3))
print(c)

[[ 11   1   3]
 [111   6   8]
 [  2   6  10]
 [  7   5   3]
 [ 10   6   9]]


In [85]:
c.resize((5, 2), refcheck=False)
print(c)

[[ 11   1]
 [  3 111]
 [  6   8]
 [  2   6]
 [ 10   7]]


In [86]:
c.resize((5, 3), refcheck=False)
print(c)

[[ 11   1   3]
 [111   6   8]
 [  2   6  10]
 [  7   0   0]
 [  0   0   0]]


In [77]:
c.T

array([[ 11,   8,   5],
       [  1,   2,   3],
       [  3,   6,  10],
       [111,  10,   6],
       [  6,   7,   9]])

In [78]:
c_flat.shape

(15,)

In [81]:
c_flat.reshape((12, 3))

ValueError: cannot reshape array of size 15 into shape (12,3)

In [80]:
c_flat

array([ 11,   1,   3, 111,   6,   8,   2,   6,  10,   7,   5,   3,  10,
         6,   9])

In [91]:
help(np.append)

Help on function append in module numpy:

append(arr, values, axis=None)
    Append values to the end of an array.
    
    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.
    
    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    delete : Delet

In [92]:
a = np.arange(1, 10).reshape((3, 3))
b = np.arange(10, 19).reshape((3, 3))
result = np.append(a, b)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [95]:
result.shape

(18,)

In [93]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [96]:
result = np.append(a, b, axis=0)
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [97]:
result.shape

(6, 3)

In [98]:
result = np.append(a, b, axis=1)
result

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [99]:
result.shape

(3, 6)

In [103]:
b = np.random.randn(6, 3)
test = np.append(a, b, axis=0)
test

array([[ 1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ],
       [ 7.        ,  8.        ,  9.        ],
       [-0.02084865, -0.40023121,  0.62827263],
       [-0.24498422,  0.664492  , -0.35348711],
       [-1.39396197,  0.47326605,  0.76341092],
       [ 0.77024391,  2.1395452 ,  0.71824208],
       [-0.69828051, -0.30121697,  0.0373272 ],
       [-0.43352837, -0.55418489,  0.70755623]])

In [104]:
test = np.append(a, b, axis=1)
test

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 6

In [108]:
np.insert(a, 1, 999)

array([  1, 999,   2,   3,   4,   5,   6,   7,   8,   9])

In [109]:
# broadcasting 되어서 값이 추가된다
np.insert(a, 1, 999, axis=0)

array([[  1,   2,   3],
       [999, 999, 999],
       [  4,   5,   6],
       [  7,   8,   9]])

In [110]:
np.insert(a, 1, [999, 998, 997], axis=0)

array([[  1,   2,   3],
       [999, 998, 997],
       [  4,   5,   6],
       [  7,   8,   9]])

In [111]:
np.insert(a, 1, [999, 998], axis=0)

ValueError: could not broadcast input array from shape (1,2) into shape (1,3)

In [112]:
np.insert(a, 1, 999, axis=1)

array([[  1, 999,   2,   3],
       [  4, 999,   5,   6],
       [  7, 999,   8,   9]])

In [113]:
np.insert(a, 1, [999, 998, 997], axis=1)

array([[  1, 999,   2,   3],
       [  4, 998,   5,   6],
       [  7, 997,   8,   9]])

In [114]:
help(np.delete)

Help on function delete in module numpy:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : slice, int or array of ints
        Indicate indices of sub-arrays to remove along the specified axis.
    
        .. versionchanged:: 1.19.0
            Boolean indices are now treated as a mask of elements to remove,
            rather than being cast to the integers 0 and 1.
    
    axis : int, optional
        The axis along which to delete the subarray defined by `obj`.
        If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
    See Also

In [115]:
np.delete(a, 1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.delete(a, 1, axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [117]:
np.delete(a, 1, axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

In [105]:
help(np.insert)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [119]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
   

In [120]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
b

array([[-0.02084865, -0.40023121,  0.62827263],
       [-0.24498422,  0.664492  , -0.35348711],
       [-1.39396197,  0.47326605,  0.76341092],
       [ 0.77024391,  2.1395452 ,  0.71824208],
       [-0.69828051, -0.30121697,  0.0373272 ],
       [-0.43352837, -0.55418489,  0.70755623]])

In [123]:
np.concatenate((a, b), axis=None)

array([ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ,
        6.        ,  7.        ,  8.        ,  9.        , -0.02084865,
       -0.40023121,  0.62827263, -0.24498422,  0.664492  , -0.35348711,
       -1.39396197,  0.47326605,  0.76341092,  0.77024391,  2.1395452 ,
        0.71824208, -0.69828051, -0.30121697,  0.0373272 , -0.43352837,
       -0.55418489,  0.70755623])

In [124]:
np.concatenate((a, b))

array([[ 1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ],
       [ 7.        ,  8.        ,  9.        ],
       [-0.02084865, -0.40023121,  0.62827263],
       [-0.24498422,  0.664492  , -0.35348711],
       [-1.39396197,  0.47326605,  0.76341092],
       [ 0.77024391,  2.1395452 ,  0.71824208],
       [-0.69828051, -0.30121697,  0.0373272 ],
       [-0.43352837, -0.55418489,  0.70755623]])

In [127]:
np.concatenate((a, b.T), axis=1)

array([[ 1.        ,  2.        ,  3.        , -0.02084865, -0.24498422,
        -1.39396197,  0.77024391, -0.69828051, -0.43352837],
       [ 4.        ,  5.        ,  6.        , -0.40023121,  0.664492  ,
         0.47326605,  2.1395452 , -0.30121697, -0.55418489],
       [ 7.        ,  8.        ,  9.        ,  0.62827263, -0.35348711,
         0.76341092,  0.71824208,  0.0373272 ,  0.70755623]])

In [128]:
np.concatenate((a, b.reshape(3, 6)), axis=1)

array([[ 1.        ,  2.        ,  3.        , -0.02084865, -0.40023121,
         0.62827263, -0.24498422,  0.664492  , -0.35348711],
       [ 4.        ,  5.        ,  6.        , -1.39396197,  0.47326605,
         0.76341092,  0.77024391,  2.1395452 ,  0.71824208],
       [ 7.        ,  8.        ,  9.        , -0.69828051, -0.30121697,
         0.0373272 , -0.43352837, -0.55418489,  0.70755623]])

In [129]:
help(np.vstack)

Help on function vstack in module numpy:

vstack(tup)
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays, will be at least 2-D.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis

In [134]:
np.hstack((a, b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 6

In [135]:
np.hstack((a, b.T))

array([[ 1.        ,  2.        ,  3.        , -0.02084865, -0.24498422,
        -1.39396197,  0.77024391, -0.69828051, -0.43352837],
       [ 4.        ,  5.        ,  6.        , -0.40023121,  0.664492  ,
         0.47326605,  2.1395452 , -0.30121697, -0.55418489],
       [ 7.        ,  8.        ,  9.        ,  0.62827263, -0.35348711,
         0.76341092,  0.71824208,  0.0373272 ,  0.70755623]])

In [137]:
help(np.split)

Help on function split in module numpy:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays as views into `ary`.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    -------
    sub-arrays : list 

In [142]:
np.hsplit(a, 3)[1]

array([[2],
       [5],
       [8]])

In [144]:
np.hsplit(a, 1)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [145]:
a = np.arange(1, 25).reshape((4, 6))
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [146]:
# [1, 3, 5] -> 0:1, 1:3, 3:5, 5: -> 0, 1~2, 3~4, 5~
np.hsplit(a, [1, 3, 5])

[array([[ 1],
        [ 7],
        [13],
        [19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]]),
 array([[ 6],
        [12],
        [18],
        [24]])]

In [151]:
a = ([1, 2, 3], [4, 5, 6], [7, 8, 9]) # 파이썬 튜플
# np.hsplit 함수 내부에서 ndim을 확인하는 것 같습니다
# 그래서 np.hsplit 함수에 tuple이 들어가면 에러가 발생합니다 
# 에러가 발생하니까 numpy의 array로 일단 바꿔줍니다
a = np.array(a) # np array로 바꿔준다음에
np.hsplit(a, [1, 3, 5]) # 함수를 실행하는데 결과를 보시면 array([]), array([]) 가 있어요
# a는 열이 세 개 있습니다 (0번열, 1번열, 2번열)
# hsplit 함수에 들어간 [1, 3, 5]의 뜻은, :1, 1:3, 3:5, 5: 입니다 
# :1 -> 0번
# 1:3 -> 1번, 2번
# 3:5 -> 3번, 4번
# 5: -> 5번부터 끝까지 
# 근데 a에 열이 3개만 있잖아요
# 그래서 3:5, 5: 가 없어요 -> 비어있는 어레이로 일단 결과를 줬습니다

[array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]]),
 array([], shape=(3, 0), dtype=int64),
 array([], shape=(3, 0), dtype=int64)]