In [1]:
import numpy as np 

In [2]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [3]:
a = np.random.randint(1, 20, size=(2, 3))
b = np.random.randint(1, 20, size=(2, 3))

In [4]:
a

array([[17, 16, 14],
       [12, 13,  9]])

In [5]:
b

array([[12, 10, 11],
       [ 2, 16, 19]])

In [6]:
a + b

array([[29, 26, 25],
       [14, 29, 28]])

In [7]:
np.add(a, b)

array([[29, 26, 25],
       [14, 29, 28]])

In [8]:
a - b

array([[  5,   6,   3],
       [ 10,  -3, -10]])

In [9]:
np.subtract(a, b)

array([[  5,   6,   3],
       [ 10,  -3, -10]])

In [10]:
c = np.random.randint(1, 20, size=(3, 3))
c

array([[ 8,  8,  7],
       [ 8, 13, 13],
       [11,  4,  9]])

In [11]:
a + c

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [12]:
a

array([[17, 16, 14],
       [12, 13,  9]])

In [15]:
a + np.full((2, 3), 10)

array([[27, 26, 24],
       [22, 23, 19]])

In [16]:
a + 10

array([[27, 26, 24],
       [22, 23, 19]])

In [17]:
a

array([[17, 16, 14],
       [12, 13,  9]])

In [18]:
b

array([[12, 10, 11],
       [ 2, 16, 19]])

In [19]:
# numpy array *: element-wise로 계산됩니다
a * b

array([[204, 160, 154],
       [ 24, 208, 171]])

In [21]:
np.multiply(a, b)

array([[204, 160, 154],
       [ 24, 208, 171]])

In [22]:
# numpy array /: element-wise로 계산
a / b

array([[1.41666667, 1.6       , 1.27272727],
       [6.        , 0.8125    , 0.47368421]])

In [24]:
np.divide(a, b)

array([[1.41666667, 1.6       , 1.27272727],
       [6.        , 0.8125    , 0.47368421]])

참고사항
- 가끔식 5가 나와야 하는데 4.99999999999456767453 이렇게 나오는 경우가 있습니다 
- 0이랑 1로 실수를 만드려다 보니까 저런 식으로 오차가 생길 때가 있다 

In [26]:
# exponential 제곱이 행렬의 원소에 대해서 각각 제곱된다 (element-wise)
a = np.random.randint(1, 10, size=(2, 3))
np.exp(a)

array([[  54.59815003,  403.42879349, 8103.08392758],
       [  20.08553692,  148.4131591 ,  148.4131591 ]])

In [27]:
a

array([[4, 6, 9],
       [3, 5, 5]])

## exponential 
* exponential -> 자연대수 e 라는 숫자가 있습니다 
* 중력가속도 g = 9.8
* 수학자 오일러 (euler) -> e = 2.718
* 2.718의 제곱 -> e^2
* 1e-4 -> 이 때의 e는 10이에요

In [34]:
help(np.sqrt)

Help on ufunc object:

sqrt = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array 

In [35]:
# sqrt: square root 의 줄임말
# root를 씌운다 -> 루트 4 = 2 
# 4 ** (0.5) = 2
np.sqrt(a)

array([[2.        , 2.44948974, 3.        ],
       [1.73205081, 2.23606798, 2.23606798]])

In [36]:
a

array([[4, 6, 9],
       [3, 5, 5]])

In [37]:
# element-wise로 계산
# log_e 4 = 1.38629
np.log(a)

array([[1.38629436, 1.79175947, 2.19722458],
       [1.09861229, 1.60943791, 1.60943791]])

In [40]:
# sin, cos, tan 다 element-wise
np.sin(a)

array([[-0.7568025 , -0.2794155 ,  0.41211849],
       [ 0.14112001, -0.95892427, -0.95892427]])

In [41]:
a

array([[4, 6, 9],
       [3, 5, 5]])

In [42]:
b

array([[12, 10, 11],
       [ 2, 16, 19]])

In [44]:
# b.T => b를 transpose (행렬 뒤집기)
np.dot(a, b.T)

array([[207, 275],
       [141, 181]])

In [45]:
np.dot(a, b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [46]:
a

array([[4, 6, 9],
       [3, 5, 5]])

In [52]:
b = np.random.randint(1, 10, size=(2, 3))
b

array([[4, 8, 2],
       [4, 6, 8]])

In [53]:
# element-wise로 비교
a == b

array([[ True, False, False],
       [False, False, False]])

In [54]:
a != b

array([[False,  True,  True],
       [ True,  True,  True]])

In [55]:
a > b

array([[False, False,  True],
       [False, False, False]])

In [56]:
a < b

array([[False,  True, False],
       [ True,  True,  True]])

In [57]:
a >= b

array([[ True, False,  True],
       [False, False, False]])

In [58]:
# array가 같은지를 확인
np.array_equal(a, b)

False

In [59]:
a

array([[4, 6, 9],
       [3, 5, 5]])

In [60]:
a.sum()

32

In [61]:
# axis=0 -> 2*3 행렬에서 size 3짜리 벡터가 나옵니다 -> 컬럼 갯수 만큼의 아웃풋이 나옵니다 
# -> 행을 없애는 쪽으로 계산이 됩니다

# axis=0 -> 제일 큰 덩어리 -> 제일 큰 덩어리끼리 더한다
a.sum(axis=0)

array([ 7, 11, 14])

In [62]:
# axis=1 -> 2*3 행렬에서 size 2짜리 벡터가 나옵니다 -> 행 갯수 만큼의 아웃풋이 나옵니다 
# -> 컬럼을 없애는 쪽으로 계산이 됩니다 

# axis=1 -> 제일 큰거에서 하나 작은 덩어리 -> 작은 덩어리를 더해준다 
a.sum(axis=1)

array([19, 13])

In [63]:
arr = np.random.randint(1, 5, size=(2, 3, 4))
arr

array([[[3, 2, 3, 3],
        [3, 2, 3, 3],
        [1, 3, 1, 4]],

       [[1, 1, 3, 2],
        [4, 3, 4, 4],
        [3, 2, 2, 1]]])

In [64]:
arr.sum(axis=0) # 결과물의 shape은 3, 4

array([[4, 3, 6, 5],
       [7, 5, 7, 7],
       [4, 5, 3, 5]])

In [65]:
arr.sum(axis=1) # 결과물의 shape은 2, 4

array([[ 7,  7,  7, 10],
       [ 8,  6,  9,  7]])

In [66]:
arr.sum(axis=2) # 결과물의 shape은 2, 3

array([[11, 11,  9],
       [ 7, 15,  8]])

In [67]:
a

array([[4, 6, 9],
       [3, 5, 5]])

In [68]:
# cumsum -> cumulative sum 
# cumulative 여서 압축을 못시킵니다 ㅠㅜ
np.cumsum(a)

array([ 4, 10, 19, 22, 27, 32])

In [69]:
# cumsum의 경우 axis를 지정했을 때, 결과물의 shape은 동일합니다
np.cumsum(a, axis=0)

array([[ 4,  6,  9],
       [ 7, 11, 14]])

In [70]:
np.cumsum(a, axis=1)

array([[ 4, 10, 19],
       [ 3,  8, 13]])

In [73]:
a

array([[4, 6, 9],
       [3, 5, 5]])

In [71]:
a.max()

9

In [72]:
a.max(axis=0)

array([4, 6, 9])

In [76]:
a.max(axis=1)

array([9, 5])

In [77]:
# std: standard deviation, 표준편차

In [78]:
a 

array([[4, 6, 9],
       [3, 5, 5]])

In [87]:
b = np.random.randint(1, 5, size=(1, 2))
b

array([[1, 3]])

In [88]:
b + a

ValueError: operands could not be broadcast together with shapes (1,2) (2,3) 

In [90]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [92]:
arr = np.random.rand(2, 3, 4)
arr

array([[[0.45778803, 0.83111792, 0.54704893, 0.34226782],
        [0.74824561, 0.96346616, 0.74017007, 0.25959195],
        [0.37775088, 0.44395633, 0.51986148, 0.29511767]],

       [[0.10268014, 0.0764922 , 0.82445424, 0.34346683],
        [0.95930832, 0.36089123, 0.25329536, 0.93104261],
        [0.38478687, 0.22541767, 0.55626417, 0.26753188]]])

In [93]:
arr[-1][-1][-1]

0.26753187798918776

In [94]:
arr[-1, -1, -1]

0.26753187798918776

In [95]:
arr[1, 2, 3]

0.26753187798918776

In [97]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [98]:
arr2 = np.random.randint(10, 100, size=(4, 4))
arr2

array([[36, 91, 99, 21],
       [98, 38, 60, 38],
       [32, 57, 75, 70],
       [91, 77, 19, 91]])

In [99]:
arr2_transpose = arr2.transpose()
arr2_transpose = arr2.T

In [100]:
arr2_reshape = arr2_transpose.reshape((2, 8))
arr2_reshape

array([[36, 98, 32, 91, 91, 38, 57, 77],
       [99, 60, 75, 19, 21, 38, 70, 91]])

In [104]:
# 수평 방향으로 [:2], [2:5], [5:7], [7:] 형태가 되도록 나누어라.
np.hsplit(arr2_reshape, [2, 5, 7])

[array([[36, 98],
        [99, 60]]),
 array([[32, 91, 91],
        [75, 19, 21]]),
 array([[38, 57],
        [38, 70]]),
 array([[77],
        [91]])]

In [107]:
# [10, 100) 범위 내에서 shape (4, 6)인 두 배열을 정의하고 두 배열의 내적을 구하여라.
arr1 = np.random.randint(10, 100, size=(4, 6))
arr2 = np.random.randint(10, 100, size=(4, 6))
arr_dot1 = np.dot(arr1, arr2.T) # (4, 4)
arr_dot2 = np.dot(arr1.T, arr2) # (6, 6)

In [108]:
np.mean(arr_dot1, axis=0)

array([18889.25, 11841.5 , 13640.  , 13620.25])

In [109]:
np.std(arr_dot1, axis=0)

array([2647.62293152, 1227.15575621, 2260.20297761, 3750.38867152])

In [110]:
# 구한 평균과 표준편차를 이용하여 해당 배열을 정규화하여라. (Z score normalization)
(arr_dot1 - np.mean(arr_dot1, axis=0)) / np.std(arr_dot1, axis=0)

array([[-1.55998422, -1.09317826, -1.2702399 , -0.39202603],
       [ 1.11864494,  0.32554955,  1.38571625,  1.57523673],
       [-0.10924894,  1.48025219, -0.5371199 , -0.01499845],
       [ 0.55058822, -0.71262348,  0.42164355, -1.16821225]])

In [111]:
(arr_dot1 - np.mean(arr_dot1)) / np.std(arr_dot1)

array([[ 0.0701128 , -1.0728936 , -1.00070089, -0.6300759 ],
       [ 1.97342376, -0.60565384,  0.61035039,  1.34999012],
       [ 1.10093872, -0.22536737, -0.55600458, -0.25059456],
       [ 1.56978872, -0.94756277,  0.02556266, -1.41131366]])

In [112]:
(arr_dot1 - np.mean(arr_dot1, axis=1)) / np.std(arr_dot1, axis=1)

array([[ 1.60849403, -1.98409404, -1.59286954, -0.38487259],
       [ 5.81090319, -1.49743474,  0.92808903,  1.35028779],
       [ 3.88450271, -1.10134271, -0.89701274, -0.05232762],
       [ 4.91969854, -1.85355418,  0.01301844, -1.06948249]])