In [1]:
import numpy as np

ppt 수정 resize 예시가 2,3,바뀜 27page
34 page axis =1

# 3. Numpy 배열 변환

### 1) NumPy 배열 전치
#### transpose() 전치행렬

In [4]:
a = np.array([[1,1,3],[2,2,2]])
a

array([[1, 1, 3],
       [2, 2, 2]])

In [5]:
a.T

array([[1, 2],
       [1, 2],
       [3, 2]])

In [6]:
a.transpose()

array([[1, 2],
       [1, 2],
       [3, 2]])

In [7]:
a

array([[1, 1, 3],
       [2, 2, 2]])

### 2) NumPy 배열 크기 변환
#### flatten()
n차원 배열을 1차원 배열로 바꾸는 함수.

In [11]:
a = np.array([[[1,2],[3,4]]])
print(a.shape)
b=a.flatten()
print(b)
print(b.shape)

(1, 2, 2)
[1 2 3 4]
(4,)


In [15]:
a[0,0]=0
a

array([[[0, 0],
        [3, 4]]])

In [16]:
b

array([1, 2, 3, 4])

#### ravel()
n차원 배열의 1차원 배열 view를 제공하는 함수.
변환된 배열은 기존 배열을 참조하므로 원본 배열의 값이 변경될 경우 변환된 배열의 값도 함께 변경된다.

In [12]:
c = np.array([[1,2],[3,4]])
d=c.ravel()
print(d)

[1 2 3 4]


In [13]:
c[0,0]=3
c

array([[3, 2],
       [3, 4]])

In [14]:
d

array([3, 2, 3, 4])

#### reshape()
- 배열의 shape를 변경함
- 수정 전후의 전체 요소 개수가 일치하지 않는다면 ValueError.


In [32]:
a = np.array([[[1,2,3,4,5],[8,9,10,11,12]],
             [[4,5,6,7,8],[10,11,12,13,14]]])
a.shape

(2, 2, 5)

In [33]:
a

array([[[ 1,  2,  3,  4,  5],
        [ 8,  9, 10, 11, 12]],

       [[ 4,  5,  6,  7,  8],
        [10, 11, 12, 13, 14]]])

In [34]:
a.reshape((4,5))

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14]])

In [35]:
a

array([[[ 1,  2,  3,  4,  5],
        [ 8,  9, 10, 11, 12]],

       [[ 4,  5,  6,  7,  8],
        [10, 11, 12, 13, 14]]])

In [18]:
b=a.reshape((4,5))
b

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14]])

In [19]:
b.shape

(4, 5)

In [21]:
c=a.reshape(5,5)

ValueError: cannot reshape array of size 20 into shape (5,5)

#### resize()
배열의 shape를 변경함.
1. 수정 전후의 전체 요소 개수가 일치하는 경우


In [36]:
a=np.random.randint(1,10,(2,6))
a

array([[9, 1, 5, 7, 2, 9],
       [8, 5, 9, 3, 9, 9]])

In [37]:
a.resize(6,2)
a

array([[9, 1],
       [5, 7],
       [2, 9],
       [8, 5],
       [9, 3],
       [9, 9]])

In [38]:
a.resize((3,3))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

#### resize()
2. 수정 전후의 전체 요소 개수가 일치하지 않고 줄어드는 경우: 삭제

In [30]:
a=np.random.randint(1,10,(2,6))
a.resize(3,3)

In [31]:
a

array([[7, 3, 9],
       [8, 5, 6],
       [6, 3, 2]])

#### resize()
배열의 shape를 변경함.
3. 수정 전후의 전체 요소 개수가 일치하지 않고 늘어나는 경우: 0으로 초기화


In [1]:
import numpy as np

In [2]:
newA = np.random.randint(1,10,(2,6))
newA

array([[6, 4, 7, 7, 4, 8],
       [9, 4, 3, 2, 9, 2]])

In [4]:
newA.resize((2,10),refcheck=False)
newA

array([[6, 4, 7, 7, 4, 8, 9, 4, 3, 2],
       [9, 2, 0, 0, 0, 0, 0, 0, 0, 0]])

### 3) NumPy 배열 추가, 삭제
#### append(arr, values, axis=None)
배열의 끝에 값을 추가
1. axis 지정 없이 추가: 1차원 배열로 변형되어 추가됨.

In [7]:
a= np.arange(1,10).reshape(3,3)
b= np.arange(10,19).reshape(3,3)

In [9]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [8]:
result=np.append(a,b)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

2. axis =0
행이 늘어남

In [10]:
result=np.append(a,b,axis=0)
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

3. axis =1 
열이 늘어남

In [11]:
result=np.append(a,b,axis=1)
result

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

#### insert(arr, obj, values, axis=None)
배열의 axis 방향 obj번째 index에 요소 추가 (axis=None이면 1차원 변환)
1.1. axis 지정 없이 추가: 1차원 배열로 변형되어 추가됨.

In [14]:
a=np.arange(1,10).reshape(3,3)
print(a)
b=np.insert(a,1,99)
print(b)
c=np.insert(a,1,99,axis=0)
print(c)
d=np.insert(a,1,99,axis=1)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1 99  2  3  4  5  6  7  8  9]
[[ 1  2  3]
 [99 99 99]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 99  2  3]
 [ 4 99  5  6]
 [ 7 99  8  9]]


#### delete(arr, obj, axis=None)
배열의 axis 방향 obj번째 index의 요소 제거 (axis=None이면 1차원 변환)

In [16]:
a=np.arange(1,10).reshape(3,3)
print(a)
print()
b=np.delete(a,1)
print(b)
print()
c=np.delete(a,1,axis=0)
print(c)
print()
d=np.delete(a,1,axis=1)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 3 4 5 6 7 8 9]

[[1 2 3]
 [7 8 9]]

[[1 3]
 [4 6]
 [7 9]]


### 4) NumPy 배열 결합
#### concatenate((a1, a2, …), axis=0)
axis 방향으로 a1, a2, … 배열을 결합

In [18]:
a = np.arange(1,7).reshape((2,3))
b = np.arange(7,13).reshape((2,3))
c = np.arange(13,19).reshape((2,3))
result = np.concatenate((a,b,c),axis=0)
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [19]:
result = np.concatenate((a,b,c),axis=1)
result

array([[ 1,  2,  3,  7,  8,  9, 13, 14, 15],
       [ 4,  5,  6, 10, 11, 12, 16, 17, 18]])

#### vstack(tup)
튜플로 설정된 여러 배열을 수직 방향(axis=0)으로 연결

In [21]:
a = np.arange(1,7).reshape((2,3))
b = np.arange(7,13).reshape((2,3))
result = np.vstack((a,b))
result


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### hstack(tup)
튜플로 설정된 여러 배열을 수평 방향(axis=1)으로 연결

In [22]:
a = np.arange(1,7).reshape((2,3))
b = np.arange(7,13).reshape((2,3))
result = np.hstack((a,b))
result


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 5) NumPy 배열 분리
#### hsplit(arr, indices_or_sections)
배열을 수평 방향(axis=1)으로 분할하는 함수

In [25]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [24]:
a = np.arange(1,25).reshape((4,6))
r1,r2,r3 = np.hsplit(a,3)
print(r1,end="\n\n")
print(r2,end="\n\n")
print(r3,end="\n\n")

[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]]

[[ 3  4]
 [ 9 10]
 [15 16]
 [21 22]]

[[ 5  6]
 [11 12]
 [17 18]
 [23 24]]



In [29]:

r1,r2= np.hsplit(a,2)
print(r1,end="\n\n")
print(r2,end="\n\n")

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]

[[ 4  5  6]
 [10 11 12]
 [16 17 18]
 [22 23 24]]




#### hsplit(arr, indices_or_sections)
배열을 수평 방향(axis=1)으로 분할하는 함수

In [30]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [46]:
r1,r2,r3,r4 = np.hsplit(a,[0,3,7])

In [47]:
r1

array([], shape=(4, 0), dtype=int32)

In [48]:
r2

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [49]:
r3

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])

In [50]:
r4

array([], shape=(4, 0), dtype=int32)

#### vsplit(arr, indices_or_sections)
배열을 수직 방향(axis=0)으로 분할하는 함수

#### vsplit(arr, indices_or_sections)
배열을 수직 방향(axis=0)으로 분할하는 함수

In [51]:
a = np.arange(1,25).reshape((4,6))
r1,r2 = np.vsplit(a,2)
print(r1,end="\n\n")
print(r2,end="\n\n")

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[13 14 15 16 17 18]
 [19 20 21 22 23 24]]

