In [ ]:
import numpy as np

# 4. NumPy 배열 연산
### 1) NumPy 배열 산술 연산
#### 사칙연산

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[8,7,6,5],[4,3,2,1]])

In [ ]:
print(a)
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[[8 7 6 5]
 [4 3 2 1]]


In [ ]:
a+b

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

In [ ]:
np.add(a,b)

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

In [ ]:
# array shape 변경
c = np.array([[1,2,3],[5,6,7]])
d = np.array([[8,7,6,5],[4,3,2,1]])

In [ ]:
print(c)
print(d)
print(c+d)

[[1 2 3]
 [5 6 7]]
[[8 7 6 5]
 [4 3 2 1]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 

In [ ]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[8,7,6,5],[4,3,2,1]])

In [ ]:
print(a)
print(b)
print(a-b)
print(np.subtract(a,b))

[[1 2 3 4]
 [5 6 7 8]]
[[8 7 6 5]
 [4 3 2 1]]
[[-7 -5 -3 -1]
 [ 1  3  5  7]]
[[-7 -5 -3 -1]
 [ 1  3  5  7]]


In [ ]:
print(a)
print(b)
print(a*b)
print(np.multiply(a,b))

[[1 2 3 4]
 [5 6 7 8]]
[[8 7 6 5]
 [4 3 2 1]]
[[ 8 14 18 20]
 [20 18 14  8]]
[[ 8 14 18 20]
 [20 18 14  8]]


In [ ]:
print(a)
print(b)
print(a/b)
print(np.divide(a,b))

[[1 2 3 4]
 [5 6 7 8]]
[[8 7 6 5]
 [4 3 2 1]]
[[0.125      0.28571429 0.5        0.8       ]
 [1.25       2.         3.5        8.        ]]
[[0.125      0.28571429 0.5        0.8       ]
 [1.25       2.         3.5        8.        ]]


#### 지수, 제곱근, 로그

In [ ]:
print(b)
print(np.exp(b))

[[8 7 6 5]
 [4 3 2 1]]
[[2.98095799e+03 1.09663316e+03 4.03428793e+02 1.48413159e+02]
 [5.45981500e+01 2.00855369e+01 7.38905610e+00 2.71828183e+00]]


In [ ]:
print(b)
print(np.sqrt(b))

[[8 7 6 5]
 [4 3 2 1]]
[[2.82842712 2.64575131 2.44948974 2.23606798]
 [2.         1.73205081 1.41421356 1.        ]]


In [ ]:
b[0][0]=16
print(np.sqrt(b))

[[4.         2.64575131 2.44948974 2.23606798]
 [2.         1.73205081 1.41421356 1.        ]]


In [ ]:
# 로그 (base=e)
print(a)
print(np.log(a))

[[1 2 3 4]
 [5 6 7 8]]
[[0.         0.30103    0.47712125 0.60205999]
 [0.69897    0.77815125 0.84509804 0.90308999]]


#### 삼각함수

In [ ]:
#sin
print(np.sin(a))
#cos
print(np.cos(a))
#tan
print(np.tan(a))

[[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825]]
[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003]]
[[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
 [-3.38051501 -0.29100619  0.87144798 -6.79971146]]


#### 내적

In [ ]:
a= np.arange(1,10).reshape(3,3)
b= np.arange(9,0,-1).reshape(3,3)

In [ ]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(a)
print(b)
print(np.dot(a,b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
x=np.eye(3)

In [ ]:
print(a)
print(x)
print(np.dot(a,x))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 2) 배열 비교 연산
#### 요소별 비교

In [ ]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(9,0,-1).reshape(3,3)

In [ ]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]



#### 배열 비교

In [ ]:
a==b

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [ ]:
a=b

In [ ]:
a

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
a>b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
a>=b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
a!=b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
c=a

In [ ]:
print(np.array_equal(a,b))
print(np.array_equal(a,c))

False
True


In [ ]:
a[0][0]=100
print(np.array_equal(a,c))

True


In [ ]:
c

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

### 3) NumPy 배열 집계 함수
집계 함수(Aggregate Functions)들은 axis를 기준으로 계산되며, axis를 지정하지 않을 경우 axis=None이다.
![image-2.png](attachment:image-2.png)

In [ ]:
#합계 np.sum()
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a)
print(a.sum())
print(np.sum(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
45


In [ ]:
print(a.sum(axis=0),np.sum(a,axis=0))

[12 15 18] [12 15 18]


In [ ]:
print(a.sum(0),np.sum(a,0))

[12 15 18] [12 15 18]


In [ ]:
print(a.sum(axis=1),np.sum(a,axis=1))

[ 6 15 24] [ 6 15 24]


#### 누적합계  cumsum()

In [ ]:
print(np.cumsum(a))

[ 1  3  6 10 15 21 28 36 45]


In [ ]:
print(np.cumsum(a,axis=0))
print(a.cumsum(axis=1))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


#### 최대값 max() / 최소값 min()

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(a.max(), np.max(a))

9 9


In [ ]:
print(a.max(axis=0))
print(np.max(a,axis=0))

[7 8 9]
[7 8 9]


In [ ]:
a = np.array([[3,2,1],
              [1,2,3],
              [1,2,3]])
print(a)
print(a.max(axis=0))

[[3 2 1]
 [1 2 3]
 [1 2 3]]
[3 2 3]


In [ ]:
b=np.array([[2,1,1],
           [4,4,4],
           [100,4,2]])
print(b)
print(b.min(axis=1))
print(b.min(axis=0))

[[  2   1   1]
 [  4   4   4]
 [100   4   2]]
[1 4 2]
[2 1 1]


In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a)
print(a.mean(),np.mean(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0 5.0


In [ ]:
print(a.mean(axis=0),np.mean(a,0))

[4. 5. 6.] [4. 5. 6.]


In [ ]:
print(a.mean(axis=1),np.mean(a,1))

[2. 5. 8.] [2. 5. 8.]


In [ ]:
print(a.std(),np.std(a))
print(a.std(axis=0),np.std(a,axis=0))
print(a.std(axis=1),np.std(a,axis=1))

2.581988897471611 2.581988897471611
[2.44948974 2.44948974 2.44948974] [2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658] [0.81649658 0.81649658 0.81649658]


### 4) NumPy 배열 Broadcasting
![image.png](attachment:image.png)

In [ ]:
a = np.arange(1,25).reshape(4,6)
print(a)
print(a+100)
print(np.add(a,100))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [ ]:
a = np.arange(3).reshape((1,3))
b = np.arange(5).reshape((5,1))
print(a)
print(b)
print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


# Quiz1

1. 다음 배열들의 shape는 어떻게 될 것인가?

![image-2.png](attachment:image-2.png)

In [ ]:
a= np.array([1,2,3])
b= np.array([[1,2],[3,4],[5,6]])
c= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(3, 2)
(2, 2, 3)


2. [0.0, 1.0) 사이의 랜덤한 값으로 이루어진 shape (2, 3, 4)인 배열을 정의하고, indexing을 사용하여 가장 마지막 요소에 접근하여라.


In [ ]:
a = np.random.rand(2,3,4)
print(a)
print(a.shape)

[[[0.399719   0.01063347 0.58089572 0.72112869]
  [0.1145843  0.8054291  0.70819117 0.81325908]
  [0.75115429 0.93583852 0.26089228 0.02298754]]

 [[0.55543912 0.13556802 0.4358858  0.31730729]
  [0.90718538 0.16214584 0.44264458 0.86187029]
  [0.01171576 0.10009657 0.61067014 0.99124445]]]
(2, 3, 4)


In [ ]:
print(a[-1][-1][-1])

0.9912444465810013


In [ ]:
a[-1,-1,-1]

0.9912444465810013

# Quiz2

1. [10, 100) 사이의 랜덤한 정수값으로 이루어진 shape (4, 4)인 배열을  정의하고
2. 이 배열의 전치행렬을 구한 후
3. shape를 (2, 8) 형태로 바꾸고
4. 수평 방향으로 [:2], [2:5], [5:7], [7:] 형태가 되도록 나누어라.

In [1]:
import numpy as np 
a =np.random.randint(10,100,size=(4,4))
print(a)

[[92 18 87 81]
 [23 92 99 16]
 [62 16 40 47]
 [13 12 27 31]]


In [2]:
#a.transpose()
a_t = a.T
print(a_t)

[[92 23 62 13]
 [18 92 16 12]
 [87 99 40 27]
 [81 16 47 31]]


In [3]:
a_t = a_t.reshape(2,8)

In [4]:
a_t

array([[92, 23, 62, 13, 18, 92, 16, 12],
       [87, 99, 40, 27, 81, 16, 47, 31]])

In [9]:
a_t.resize(3,10)

ValueError: ignored

In [8]:
a_t

array([[92, 23, 62, 13, 18, 92, 16, 12],
       [87, 99, 40, 27, 81, 16, 47, 31]])

In [ ]:
r1,r2,r3,r4 = np.hsplit(a_t,[2,5,7])

In [ ]:
print(r1)
print(r2)
print(r3)
print(r4)

[[78 89]
 [68 58]]
[[41 40 79]
 [64 58 56]]
[[70 41]
 [69 60]]
[[83]
 [17]]


# Quiz3
1. 정수 [10, 100) 범위 내에서 shape (4, 6)인 두 배열을 정의하고 두 배열의 내적을 구하여라.
2. 내적한 배열의 axis=0 방향의 평균과 표준편차를 구하여라.
3. 구한 평균과 표준편차를 이용하여 해당 배열을 정규화하여라.

In [ ]:
a = np.random.randint(10,100,size=(4,6))
b = np.random.randint(10,100,size=(4,6))

In [ ]:
print(a)
print(b)

[[57 77 31 62 75 89]
 [86 72 24 98 65 26]
 [98 58 23 27 20 40]
 [36 26 96 30 36 14]]
[[43 62 25 19 58 31]
 [10 94 90 12 24 77]
 [67 41 30 52 98 47]
 [42 85 94 51 16 25]]


In [ ]:
c = np.dot(a,b)

ValueError: shapes (4,6) and (4,6) not aligned: 6 (dim 1) != 4 (dim 0)

( 4 , 6 ) X ( 6 , 4 )=( 4 ,4 )

In [ ]:
c = np.dot(a,b.T)
print(c)

[[16287 19995 22663 18440]
 [15200 14526 22122 18676]
 [11298 12386 14878 13905]
 [ 8652 13746 12104 15202]]



정규화 공식 : 
y = (x - 평균)/표준편차

In [ ]:
c_mean=np.mean(c)
c_std =np.std(c)


In [ ]:
y = (c-c_mean)/c_std
print(y)

[[ 0.17428809  1.15794142  1.86570493  0.74543308]
 [-0.11406983 -0.29286766  1.72218917  0.80803885]
 [-1.14918723 -0.86056403 -0.19948956 -0.45760572]
 [-1.8511146  -0.49978503 -0.93537261 -0.11353927]]
